### ISSUE TITLE
Rename branch master to main

### ISSUE THREAD

**Issue by 2sn** [conradtchan/starfit#103]
@dliptai would this break anything in the scripts?

**Comment by 2sn** [comment]
@dliptai @conradtchan I t seems I cannot rename this branch not the web server since I am not the owner of the branches, or whatever rights are needed.

**Comment by conradtchan** [comment]
@2sn I have renamed `master` to `main`.

**Comment by 2sn** [comment]
Thanks.  I can do the other changes.

**Comment by 2sn** [comment]
@dliptai can you do the rename on the server?

**Comment by 2sn** [comment]
Done.
