### ISSUE TITLE
`STARFIT_DATA` should specify an additional directory rather than a replacement

### ISSUE THREAD

**Issue by dliptai** [conradtchan/starfit#47]
currently a directory can be set where the data lives, `STARFIT_DATA`, but maybe this should be to allow specifying an additional directory rather than a replacement?

_Originally posted by @2sn in https://github.com/conradtchan/starfit/issues/24#issuecomment-1279851577_

**Comment by 2sn** [comment]
@dliptai yes, I am having some second thoughts about it.  Maybe someone wanted to only use their own directory.  I will have a think about it and then implement it, if needed.  This is a feature request I can take care of.

**Comment by dliptai** [comment]
Ah, I just made a PR

**Comment by 2sn** [comment]
yes, I think this is sort-of a variation of #24
