### ISSUE TITLE
Tests can be reorganised

### ISSUE THREAD

**Issue by conradtchan** [conradtchan/starfit#48]
Currently, the filenames for tests are not descriptive, and tests are copied and pasted, whereas they could be run in a loop using 1 function

@2sn FYI - `pytest` will look for files starting with `test_`, and will run all functions in these files with names starting with `test_`. So it's okay to group all of the tests together by having several functions in one file. And for tests that follow the same format, you can have a list of arguments.

**Comment by conradtchan** [comment]
@2sn Thanks for adding those extra tests BTW. Have a look at #50 to see an example of how you can use a decorator to parameterise pytest. If you're happy with that change to your tests, feel free to merge it in. 🙂

**Comment by 2sn** [comment]
I had them put in as separate test so this running though looks like more successes.  ;-)
And one can very clearly see what fails.

**Comment by 2sn** [comment]
@conradtchan yes, it took a while to create some of these tests.

A lot more test are needed which will come over time as we have more failures in roll-out.
