### ISSUE TITLE
bug: typo -- expanduser

### ISSUE THREAD

**Issue by dliptai** [conradtchan/starfit#51]
should be expand, not exand

https://github.com/conradtchan/starfit/blob/ab3a3417e78c1562b18b0cfebba3e85fca02f476/src/starfit/__init__.py#L5-L11

**Comment by dliptai** [comment]
Found another typo

https://github.com/conradtchan/starfit/blob/d4e18ad44c1241bf7f7c7127f1ee82466f62c6c6/src/starfit/__init__.py#L8-L12

should be `is_dir`

**Comment by 2sn** [comment]
@david yes, there were annoying name changes between `os.path` and `pathlib`
