### ISSUE TITLE
Ga fails when fitting Th and U with (some) grids that have zero yields

### ISSUE THREAD

**Issue by ThomasNordlander** [conradtchan/starfit#71]
`Ga` fails when the fit includes elements that yield zeros in one of the databases. In particular this happens when fitting Th and U (e.g. using the abundances of [smss2003-1142.txt](https://github.com/conradtchan/starfit/files/9856664/smss2003-1142.txt)) with `znuc2012.S4.star.el.y.stardb.gz`. 

I think the underlying problem is that

```python
s = starfit.Single(
    filename = 'smss2003-1142.txt',
    db = 'znuc2012.S4.star.el.y.stardb.gz',
    z_max = 999,
    z_exclude = [3, 24],
    z_lolim = [21, 29],
    upper_lim = True,
    cdf = True,
    )
```
returns `inf` for all models. I think this happens because the normalisation becomes infinite. This isn't really a bug because the yields in this grid are zero Th and U for all models, so the fit is just unsuitable. 

The problem is that
```python
s = starfit.Ga(
    filename = 'smss2003-1142.txt',
    db = (
        'znuc2012.S4.star.el.y.stardb.gz',
        'rproc.just15.star.el.y.stardb.xz',
        ),
    z_max = 999,
    z_exclude = [3, 24],
    z_lolim = [21, 29],
    upper_lim = True,
    cdf = True,
    sol_size = 2,
    cover = True, 
    time_limit=20,
    )
```
runs forever, possibly for the same reason. This one really should work since Th and U should come from the second database and lighter elements from the first database.

**Comment by 2sn** [comment]
My student Kat reported the exact same issue today with some of her fits.  In her case, the issue came about because of comparison with of log values of the model abundances to the log values of the observed data.  But the former fails.  So we just set a floor in the model, say 1e-99, with is one part in 1e20 universes worth of nucleons ;-)

**Comment by 2sn** [comment]
So I will check the code.  any such element will still contribute and insane value to chi^2, although no longer infinite, but yet be ruled out.

**Comment by 2sn** [comment]
for me, the Ga still seems to run, even w/o the fix

**Comment by 2sn** [comment]
I think the GA very swiftly converges for this case.  I had tested it in the past and never saw it take forever.

**Comment by 2sn** [comment]
![xxx](https://user-images.githubusercontent.com/1273110/197709144-1e560dff-e99c-456d-a1c9-2b80b7315582.png)

**Comment by 2sn** [comment]
for this case you could also afford a full search with `partition` - definitively complete and faster than GA for the definitive answer.

**Comment by 2sn** [comment]
At least the first part is fixed by #72 , I believe (`v0.8.3` on PyPI).

**Comment by 2sn** [comment]
@ThomasNordlander feel free to re-open if GA still fails.

**Comment by ThomasNordlander** [comment]
@2sn Thanks! The 1 in 1e20 Universes fix works! Results are not very good of course, since the 99 dex error makes chi^2 explode and leads to unreasonable dilution factors of >10 dex. Now Ga finishes every time.

But yes you are right, Multi is a better idea for cases like this. I note that I find Ga to converge very rapidly here, probably in less than a second, and producing the same fit as Multi.

Yes I would be happy to see this star added to the standard list. I rewrote the comments here so they are more suitable for the public: [smss2003-1142.txt](https://github.com/conradtchan/starfit/files/9858177/smss2003-1142.txt)

**Comment by 2sn** [comment]
We probably should eventually add an option for GA to terminate when there are no more improvements for a while (some threshold in relative gain and number of generations), in case @conradtchan has not already done that.  I will need to check the code.

**Comment by conradtchan** [comment]
> We probably should eventually add an option for GA to terminate when there are no more improvements for a while

@2sn That's a good idea, and I don't think it currently exists. It also might be worth adding a stopping criteria for the number of generations (as an alternative to wall time), which would allow similar results to be obtained from different performing computers. A faster machine would be able to run more generations in the same amount of wall time.

**Comment by ThomasNordlander** [comment]
Would it be possible to make `Ga` output a progress report while running, similar to `Multi`? If so, we can just let keyboard interrupt be caught and when that happens exit out of the loop and return the current results.

**Comment by 2sn** [comment]
@ThomasNordlander I think capturing keyboard inputs in a platform-independent way is tricky. I tried this before.

Although I did some for the `StarHeat` project (@dliptai ), but may run only on Linux.

Outputs can be done, sure, while it runs in python; eventually, however, the GA may need to be re-implemented in Fortran - the calling overhead through `f2py` is just tremendous.
