### ISSUE TITLE
move starplot as method of StarFit base class

### ISSUE THREAD

**Issue by 2sn** [conradtchan/starfit#99]
@conradtchan There is a insane set o parameters passed, maybe better to add as method of StarFit base class?  Also allows for easier overwriting of parts by derived classes.  What do you think?  (no action on your side needed)

**Comment by conradtchan** [comment]
Yeah, I agree. When I wrote this I didn't really know what I was doing. It should just be a method of the base class.

**Comment by 2sn** [comment]
closed by #113
